customhost = "capstoneproj2.cfqth0dgduw9.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "capstoneproj2"
custombucket = "capstoneproj2"
customregion = "us-east-1f"
